env:
  commonjs: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  max-len:
    - off
  indent:
    - error
    - 4
  semi:
    - error
    - never
